### ISSUE TITLE
Unable to instantiate any of the param variables within textplot_wordcloud

### ISSUE THREAD

**Issue by dani-lbnl** [quanteda/quanteda_tutorials#16]
None of the parameter variables can be instantiated as in the example below:
textplot_wordcloud(my_dfm, min_size=4,  min_count =4, max_words = 10)
Error: none of these variables  "is not a graphical parameter" according to the warnings. Any thoughts? thx

**Comment by kbenoit** [comment]
It does in versions >= 1.2.0, please update, or provide a reproducible example.
